//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.GESTIONCITAS.PERSONAS.DATAACCESS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesPersonas : DbContext
    {
        public EntitiesPersonas()
            : base("EPS.GESTIONCITAS.PERSONAS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLINICAS> CLINICAS { get; set; }
        public virtual DbSet<PERSONAS> PERSONAS { get; set; }
        public virtual DbSet<PERSONAS_X_CLINICA> PERSONAS_X_CLINICA { get; set; }
        public virtual DbSet<TIPO_PERSONAS> TIPO_PERSONAS { get; set; }
    }
}
