//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.GESTIONCITAS.PERSONAS.DATAACCESS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public decimal ID_PERSONA { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public Nullable<decimal> ID_TIPO_PERSONA { get; set; }
        public Nullable<decimal> CEDULA { get; set; }
    }
}
