//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.GESTIONCITAS.PERSONAS.DATAACCESS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS_X_CLINICA
    {
        public decimal ID_PERSONAS_X_CLINICA { get; set; }
        public Nullable<decimal> ID_CLINICA { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
    }
}
