//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.GESTIONCITAS.RECETASDataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("EPS.GESTIONCITAS.RECETAS")
        {
        }
    
        public virtual DbSet<ESTADOS_RECETAS> ESTADOS_RECETAS { get; set; }
        public virtual DbSet<RECETAS> RECETAS { get; set; }
    }
}
