//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.GESTIONCITAS.RECETASDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RECETAS
    {
        [Key]
        public decimal ID_RECETA { get; set; }
        public decimal ID_MEDICO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_ESTADO { get; set; }
    }
}
