//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.GESTIONCITAS.CITASDataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Configuration;
    public partial class EntitiesCitas : DbContext
    {
        public EntitiesCitas()
            : base("EPS.GESTIONCITAS.CITAS")
        {
        }
    
        public virtual DbSet<CITAS> CITAS { get; set; }
        public virtual DbSet<ESTADOS_CITAS> ESTADOS_CITAS { get; set; }
    }
}
